[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.19.6" # Descente sur une version LTS ultra-stable pour les serveurs headless
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    
