[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.22.2"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

## Configuration des en-têtes de performance et sécurité pour le Web App
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = "*"
    
