# Fichier de configuration épuré pour forcer le déploiement de H.S.C.100
include: package:flutter/analysis_options.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - build/**

linter:
  rules:
    - avoid_print
    
